/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.core.message;

import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Represents the reason why a message was generated by an agent.
 *
 * <p>This enum helps users understand the context and state of agent execution
 * when a message is returned. Different reasons indicate different follow-up
 * actions that may be required.
 *
 * <p>Example usage:
 * <pre>{@code
 * Msg response = agent.call(userMsg).block();
 * switch (response.getGenerateReason()) {
 *     case MODEL_STOP -> System.out.println("Task completed");
 *     case TOOL_SUSPENDED -> handleSuspendedTools(response);
 *     case REASONING_STOP_REQUESTED -> handleHumanReview(response);
 *     // ...
 * }
 * }</pre>
 */
public enum GenerateReason {

    /** Model stopped normally, task completed. */
    MODEL_STOP,

    /** Model returned tool calls (internal tools, framework will continue execution). */
    TOOL_CALLS,

    /** Structured output completed. */
    STRUCTURED_OUTPUT,

    /** Tool execution was suspended, waiting for user to provide results. */
    TOOL_SUSPENDED,

    /** Reasoning phase was stopped by a Hook (PostReasoningEvent.stopAgent()). */
    REASONING_STOP_REQUESTED,

    /** Acting phase was stopped by a Hook (PostActingEvent.stopAgent()). */
    ACTING_STOP_REQUESTED,

    /**
     * Permission engine is asking the user to confirm one or more tool calls.
     *
     * <p>The returned Msg contains ToolUseBlocks with {@code state=ASKING}. The caller resumes
     * by issuing a second {@code agent.call(...)} carrying {@code ConfirmResult}s.
     */
    PERMISSION_ASKING,

    /**
     * The model asked the user for input via a tool whose {@code checkPermissions()} returned
     * {@code PermissionDecision.askUser(...)} (e.g. the built-in {@code ask_user} tool).
     *
     * <p>The returned Msg contains the pending ToolUseBlock(s) whose input carries the questions.
     * The caller resumes by issuing a second {@code agent.call(...)} whose message carries
     * {@code List<AskUserResult>} under {@code Msg.METADATA_ASK_USER_RESULTS}.
     */
    ASK_USER_ASKING,

    /**
     * The run is paused for both permission confirmations and model-initiated user questions.
     *
     * <p>The returned message contains separate pending tool-call subsets. Resume each subset with
     * its corresponding metadata payload: {@code ConfirmResult}s for permission calls and
     * {@code AskUserResult}s for question calls. Adapters that only support one pause kind must
     * preserve the other subset instead of treating this reason as a completed turn.
     */
    PERMISSION_AND_ASK_USER_ASKING,

    /**
     * A middleware requested the agent to pause via {@code RequestStopEvent}.
     *
     * <p>The caller resumes by issuing a second {@code agent.call()} with no arguments — the
     * agent picks up any pending tool calls and continues from where it stopped.
     */
    MIDDLEWARE_STOP_REQUESTED,

    /**
     * All tool calls were denied by the user and a hook requested the agent to stop.
     *
     * <p>Fired when every tool call from the most recent reasoning step was denied via HITL
     * permission confirmation and an {@code AllToolsDeniedEvent} hook
     * handler called {@code stopAgent()}.
     */
    ALL_TOOLS_DENIED,

    /** Agent was interrupted. */
    INTERRUPTED,

    /** Maximum iterations reached. */
    MAX_ITERATIONS,

    /** Tool result returned directly to the caller without a follow-up model call. */
    TOOL_RETURN_DIRECT;

    /** Maximum number of unknown-value warning states retained; package-private for tests. */
    static final int MAX_REPORTED_UNKNOWN_VALUES = 256;

    /** Maximum number of unknown-value WARN records emitted in one interval; package-private for tests. */
    static final int MAX_UNKNOWN_VALUE_WARNINGS_PER_INTERVAL = 512;

    private static final int MAX_UNKNOWN_VALUE_LENGTH = 256;
    private static final long UNKNOWN_VALUE_LOG_INTERVAL_NANOS = TimeUnit.MINUTES.toNanos(5);
    private static final Logger logger = LoggerFactory.getLogger(GenerateReason.class);
    // Access-ordered: all reads and writes must hold the map monitor.
    private static final Map<String, UnknownValueWarningState> unknownValueWarningStates =
            new LinkedHashMap<>(16, 0.75f, true);
    private static long unknownValueWarningWindowStartNanos = Long.MIN_VALUE;
    private static int unknownValueWarningsInWindow;
    private static long globallySuppressedUnknownValueWarnings;

    /**
     * Decodes a wire value without making newer reason values fatal to older readers.
     *
     * <p>Unknown values fall back to the normal completion reason, matching {@link Msg}'s
     * metadata compatibility behavior. Callers that need to distinguish unsupported pause kinds
     * should preserve the raw wire payload or upgrade before handling the turn.
     */
    @JsonCreator
    public static GenerateReason fromJson(String value) {
        if (value == null) {
            return null;
        }
        try {
            return valueOf(value);
        } catch (IllegalArgumentException ignored) {
            reportUnknownValue(value);
            return MODEL_STOP;
        }
    }

    private static void reportUnknownValue(String value) {
        UnknownValueWarningDecision decision =
                getUnknownValueWarningDecision(value, System.nanoTime());
        if (!decision.shouldWarn()) {
            return;
        }

        String reportedValue = truncateUnknownValue(value);
        if (decision.globallySuppressedCount() > 0) {
            if (decision.valueSuppressedCount() == 0) {
                logger.warn(
                        "Unknown GenerateReason '{}' received; suppressed {} additional unknown "
                                + "GenerateReason warnings during the previous interval; "
                                + "falling back to MODEL_STOP",
                        reportedValue,
                        decision.globallySuppressedCount());
            } else {
                logger.warn(
                        "Unknown GenerateReason '{}' received again after suppressing {} repeats; "
                                + "also suppressed {} additional unknown GenerateReason warnings "
                                + "during the previous interval; falling back to MODEL_STOP",
                        reportedValue,
                        decision.valueSuppressedCount(),
                        decision.globallySuppressedCount());
            }
        } else if (decision.valueSuppressedCount() == 0) {
            logger.warn(
                    "Unknown GenerateReason '{}' received; falling back to MODEL_STOP",
                    reportedValue);
        } else {
            logger.warn(
                    "Unknown GenerateReason '{}' received again after suppressing {} repeats; "
                            + "falling back to MODEL_STOP",
                    reportedValue,
                    decision.valueSuppressedCount());
        }
    }

    /**
     * Tracks an unknown value and returns its suppressed repeat count when a warning is due.
     * Returns {@code -1} while the value is still within the warning interval. The timestamp is
     * supplied by the caller so the state transition can be tested without waiting.
     */
    static long getUnknownValueSuppressedCount(String value, long nowNanos) {
        UnknownValueWarningDecision decision = getUnknownValueWarningDecision(value, nowNanos);
        return decision.shouldWarn() ? decision.valueSuppressedCount() : -1;
    }

    private static UnknownValueWarningDecision getUnknownValueWarningDecision(
            String value, long nowNanos) {
        synchronized (unknownValueWarningStates) {
            UnknownValueWarningState state = unknownValueWarningStates.get(value);
            if (state != null
                    && nowNanos - state.lastReportedAtNanos < UNKNOWN_VALUE_LOG_INTERVAL_NANOS) {
                state.suppressedCount++;
                return UnknownValueWarningDecision.suppressed();
            }

            long globallySuppressedCount = rotateUnknownValueWarningWindowIfNeeded(nowNanos);
            if (state == null) {
                if (unknownValueWarningStates.size() >= MAX_REPORTED_UNKNOWN_VALUES) {
                    Iterator<String> iterator = unknownValueWarningStates.keySet().iterator();
                    iterator.next();
                    iterator.remove();
                }
                state = new UnknownValueWarningState();
                unknownValueWarningStates.put(value, state);
            }

            if (unknownValueWarningsInWindow >= MAX_UNKNOWN_VALUE_WARNINGS_PER_INTERVAL) {
                state.lastReportedAtNanos = nowNanos;
                state.suppressedCount++;
                globallySuppressedUnknownValueWarnings++;
                return UnknownValueWarningDecision.suppressed();
            }

            long suppressedCount = state.suppressedCount;
            state.lastReportedAtNanos = nowNanos;
            state.suppressedCount = 0;
            unknownValueWarningsInWindow++;
            return new UnknownValueWarningDecision(true, suppressedCount, globallySuppressedCount);
        }
    }

    private static long rotateUnknownValueWarningWindowIfNeeded(long nowNanos) {
        if (unknownValueWarningWindowStartNanos == Long.MIN_VALUE) {
            unknownValueWarningWindowStartNanos = nowNanos;
            return 0;
        }
        if (nowNanos - unknownValueWarningWindowStartNanos < UNKNOWN_VALUE_LOG_INTERVAL_NANOS) {
            return 0;
        }

        long suppressedCount = globallySuppressedUnknownValueWarnings;
        unknownValueWarningWindowStartNanos = nowNanos;
        unknownValueWarningsInWindow = 0;
        globallySuppressedUnknownValueWarnings = 0;
        return suppressedCount;
    }

    static void clearUnknownValueWarningStatesForTest() {
        synchronized (unknownValueWarningStates) {
            unknownValueWarningStates.clear();
            unknownValueWarningWindowStartNanos = Long.MIN_VALUE;
            unknownValueWarningsInWindow = 0;
            globallySuppressedUnknownValueWarnings = 0;
        }
    }

    private static String truncateUnknownValue(String value) {
        if (value.length() <= MAX_UNKNOWN_VALUE_LENGTH) {
            return value;
        }
        return value.substring(0, MAX_UNKNOWN_VALUE_LENGTH - 3) + "...";
    }

    private static final class UnknownValueWarningState {
        private long lastReportedAtNanos;
        private long suppressedCount;
    }

    private record UnknownValueWarningDecision(
            boolean shouldWarn, long valueSuppressedCount, long globallySuppressedCount) {

        private static UnknownValueWarningDecision suppressed() {
            return new UnknownValueWarningDecision(false, 0, 0);
        }
    }
}
