{{- if .Values.mysql.enabled }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "mysql-secret") }}
{{- $rootPassword := "" }}
{{- $userPassword := "" }}
{{- if $existingSecret }}
  {{- $rootPassword = (index $existingSecret.data "MYSQL_ROOT_PASSWORD" | b64dec) }}
  {{- $userPassword = (index $existingSecret.data "MYSQL_PASSWORD" | b64dec) }}
{{- else }}
  {{- if .Values.mysql.auth.rootPassword }}
    {{- $rootPassword = .Values.mysql.auth.rootPassword }}
  {{- else }}
    {{- $rootPassword = randAlphaNum 16 }}
  {{- end }}
  {{- if .Values.mysql.auth.password }}
    {{- $userPassword = .Values.mysql.auth.password }}
  {{- else }}
    {{- $userPassword = randAlphaNum 16 }}
  {{- end }}
{{- end }}
---
# MySQL Init ConfigMap - 确保用户可以从任何 IP 连接
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  labels:
    app: mysql
data:
  # 01-init-user.sql: 在数据库创建后立即执行，确保用户权限正确
  01-init-user.sql: |
    -- 删除可能存在的 localhost 限制的用户
    DROP USER IF EXISTS '{{ .Values.mysql.auth.username }}'@'localhost';
    
    -- 确保用户可以从任何主机连接
    CREATE USER IF NOT EXISTS '{{ .Values.mysql.auth.username }}'@'%' IDENTIFIED BY '{{ $userPassword }}';
    
    -- 授予所有权限
    GRANT ALL PRIVILEGES ON {{ .Values.mysql.auth.database }}.* TO '{{ .Values.mysql.auth.username }}'@'%';
    
    -- 立即刷新权限（多次刷新确保生效）
    FLUSH PRIVILEGES;
    FLUSH PRIVILEGES;
    
    -- 强制重新加载授权表
    FLUSH TABLES;
    
    -- 再次刷新权限
    FLUSH PRIVILEGES;
    
    -- 验证用户创建成功
    SELECT CONCAT('User created: ', User, '@', Host) AS Status 
    FROM mysql.user 
    WHERE User = '{{ .Values.mysql.auth.username }}';
    
    -- 验证权限已授予
    SHOW GRANTS FOR '{{ .Values.mysql.auth.username }}'@'%';

---
# MySQL Secret: 存储敏感的数据库凭据（自动生成随机密码）
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ $rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | quote }}
  MYSQL_USER: {{ .Values.mysql.auth.username | quote }}
  MYSQL_PASSWORD: {{ $userPassword | quote }}

---
# HiMarket Server Secret: 应用专用敏感配置（使用相同的密码）
apiVersion: v1
kind: Secret
metadata:
  name: himarket-server-secret
  labels:
    app: himarket-server
type: Opaque
stringData:
  # 使用相同的 MySQL 密码变量，确保一致性
  DB_HOST: "mysql-headless-svc"
  DB_PORT: "3306"
  DB_NAME: {{ .Values.mysql.auth.database | quote }}
  DB_USERNAME: {{ .Values.mysql.auth.username | quote }}
  DB_PASSWORD: {{ $userPassword | quote }}

---
# MySQL Headless Service: 为 StatefulSet 提供稳定的网络域
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-svc
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql

---
# MySQL External Service: 暴露数据库给外部访问（可选）
{{- if .Values.mysql.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql-external-svc
spec:
  type: {{ .Values.mysql.service.external.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
{{- end }}

---
# MySQL StatefulSet: 部署 MySQL 应用
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-headless-svc"
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: {{ include "himarket.serviceAccountName" . }}
      containers:
        - name: mysql
          {{- if .Values.mysql.image.hub }}
          image: "{{ .Values.mysql.image.hub }}/{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          {{- else }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          {{- with .Values.mysql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          # 健康检查
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u{{ .Values.mysql.auth.username }}
                - -p{{ $userPassword }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mysql
                - -h
                - localhost
                - -u{{ .Values.mysql.auth.username }}
                - -p{{ $userPassword }}
                - -e
                - "SELECT 1"
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 3
      volumes:
        - name: mysql-init-scripts
          configMap:
            name: mysql-init-config

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: 
          - {{ .Values.mysql.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
        {{- if .Values.mysql.persistence.storageClass }}
        {{- if (eq "-" .Values.mysql.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
{{- end }}
