/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.builder.web.config;

import javax.sql.DataSource;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

/** Scheduler-owned schema migration, run explicitly before constructing the runtime adapter. */
final class WeixinStateSchema {
    private WeixinStateSchema() {}

    static void initialize(DataSource dataSource) {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        boolean postgres =
                Boolean.TRUE.equals(
                        jdbc.execute(
                                (ConnectionCallback<Boolean>)
                                        connection ->
                                                "PostgreSQL"
                                                        .equals(
                                                                connection
                                                                        .getMetaData()
                                                                        .getDatabaseProductName())));
        new TransactionTemplate(new DataSourceTransactionManager(dataSource))
                .executeWithoutResult(
                        status -> {
                            // Serialize first deployment across Scheduler replicas, including
                            // PostgreSQL catalog DDL.
                            if (postgres) jdbc.execute("select pg_advisory_xact_lock(184714, 1)");
                            migrate(jdbc);
                        });
    }

    private static void migrate(JdbcTemplate jdbc) {
        jdbc.execute(
                "create table if not exists builder_weixin_cursor (account_id varchar(255) primary"
                        + " key, cursor_value text not null, updated_at bigint not null)");
        jdbc.execute(
                "create table if not exists builder_weixin_context (account_id varchar(255) not"
                    + " null, peer_id varchar(255) not null,context_token text not null, updated_at"
                    + " bigint not null, primary key (account_id, peer_id))");
        jdbc.execute(
                "create table if not exists builder_weixin_lease ("
                        + "account_id varchar(255) primary key, holder_id varchar(255) not null,"
                        + "acquired_at bigint not null, expires_at bigint not null)");
        jdbc.execute(
                "alter table builder_weixin_lease add column if not exists generation bigint not"
                        + " null default 0");
        jdbc.execute(
                "create table if not exists builder_weixin_inbox ("
                        + "inbox_order bigint generated by default as identity,"
                        + "account_id varchar(255) not null, message_id varchar(512) not null,"
                        + "payload text, status varchar(16) not null,"
                        + "claim_generation bigint not null default 0, claim_id varchar(36),"
                        + "claim_until bigint not null default 0, completed_at bigint,"
                        + "primary key (account_id, message_id))");
        jdbc.execute(
                "create index if not exists builder_weixin_inbox_pending"
                        + " on builder_weixin_inbox (account_id, status, inbox_order)");
    }
}
